### ISSUE TITLE
Consider not using chai for assert in production code

### ISSUE THREAD

**Issue by wheresrhys** [polyglotted/pg-crypt#1]
It doesn't feel like appropriate use of a large testing library, and recently has caused build problems when calling `npm prune` https://github.com/Financial-Times/next-myft-page/pull/912. I'm happy to submit a PR to use node's native assert library https://nodejs.org/api/assert.html

**Comment by davidfhaines** [comment]
Thanks Rhys. Have dropped chai and released v0.10.1.

**Comment by wheresrhys** [comment]
excellent. Thanks for fixing so quickly cc @keirog
